### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by Ansh101112** [Leadlly/leadlly.mentor.web#60]
@shivang-16 assign me this issue under hacktoberfest to start working,

**Comment by shivang-16** [comment]
What home page before login? Can you explain it properly

**Comment by Ansh101112** [comment]
> What home page before login? Can you explain it properly

As I tried to login to the application it's not getting me to the home page after the successful authentication even. It stopped on saying the "free plan activated" only. 

Is the data flow for authentication has been completed if not I will love to fix this.

**Comment by shivang-16** [comment]
Mentor web flow is like this .. Authentication > Mentor details > Verfication page > Dashboard 
After admin verify the mentor then only dashboard is accessible...
Is there any problem in this flow? then share it with image

If you want we can connect on meet to discuss the issue
